### ISSUE TITLE
New Action for thehive 5 App

### ISSUE THREAD

**Issue by cloudifyopsblog** [Shuffle/Shuffle#1358]
We need to add a new action for thehive5 App, the action is to Export Case to MISP which uses the POST request to http://your-instance/api/connector/misp/export/{caseId}/{mispName}. 

**Describe the solution you'd like**
Since we already have the action for the cortex connector, we can achieve it in the similar fashion.

**Describe alternatives you've considered**
As of now we are integrating the thehive with cortex and running the analyzers to get the MISP report, this is the only way we seen which can be automated. But If this feature can be added we can use the shuffle workflow export action which can get us the MISP report and attach it to thehive case.

**Comment by frikky** [comment]
> We need to add a new action for thehive5 App, the action is to Export Case to MISP which uses the POST request to [http://your-instance/api/connector/misp/export/{caseId}/{mispName}](http://your-instance/api/connector/misp/export/%7BcaseId%7D/%7BmispName%7D).
> 
> **Describe the solution you'd like** Since we already have the action for the cortex connector, we can achieve it in the similar fashion.
> 
> **Describe alternatives you've considered** As of now we are integrating the thehive with cortex and running the analyzers to get the MISP report, this is the only way we seen which can be automated. But If this feature can be added we can use the shuffle workflow export action which can get us the MISP report and attach it to thehive case.

Hey!

If you need more functions for an app, you can fork (copy) it and add it directly yourself. We do this for customers that need actions, but don't have time to add every action to every app for all our users.

You can fork it by going to the app, and clicking "Fork" in the top right corner, OR download the app to your local instance and change it from there. If you need further assistance, please reach out to our support team :)

**Comment by cloudifyopsblog** [comment]
Is there any doc/Blog, that we can follow to add action on to the app?

Also, it will helpful if you can share some more info on how to achieve it.

**Comment by frikky** [comment]
> Not able to add the Action, I followed below steps
> 
> * Downloaded the app from https://shuffler.io/apps/5fefa1911e01a005b54f94dcb6830d82?queryID=48173afcbc26cee2c214d912f459bd39
> * In our self hosted shuffle, Under Apps->Create a new app from OpenAPI / Swagger->Uploaded the file->Continue.
> * Added the new Action,
>   
>   * Name: Export case to MISP
>   * Description: Export Case to MISP
>   * URL path / Curl statement: /api/connector/misp/export/{caseId}/{mispName}
>   * Rest of the settings as default.
> * While I save it, getting a below error
>   `Upload Error: SyntaxError: Expected ',' or '}' after property value in JSON at position 65 (line 1 column 66)`
> 
> Can you help me out here.

Interesting - you may have stumbled over a generator bug then. What frontend version are you on? (check docker-compose.yml file next to image: ... shuffle-frontend/<version>

Could you verify if the same editing works on our cloud or not? If it works, then you may just have to upgrade to a later version.

**Comment by cloudifyopsblog** [comment]
- We have self-hosted the shuffle on Kubernetes Cluster, so each of these components is running on each pod. 
- We are using the 1.3.1 version for the backend, frontend, and orborus.
- I did edit the app in cloud and it is working. But when I deploy the latest version of shuffle on my Kubernetes, I am not able to login to the shuffle UI at all.

So I believe it's better I can rectify the issue which I am facing now the issue is with the shuffle-app-builder,
- I see when I try to build app and click save, a K8s job is getting created with a node selector added to it. 
   - The pod created through the job is failing, below are logs from the pod
   ```DEBU[0000] Getting source context from dir:///app/generated/TheHive_5_v1-a1c456ec161b42be5c18f9f5a556d1a6/
DEBU[0000] Build context located at /app/generated/TheHive_5_v1-a1c456ec161b42be5c18f9f5a556d1a6/
DEBU[0000] Copying file /app/generated/TheHive_5_v1-a1c456ec161b42be5c18f9f5a556d1a6/Dockerfile to /kaniko/Dockerfile
error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "192.168.29.16:5000/frikky/shuffle:thehive_5_v1_1.1.0": creating push check transport for 192.168.29.16:5000 failed: Get "https://192.168.29.16:5000/v2/": dial tcp 192.168.29.16:5000: i/o timeout; Get "http://192.168.29.16:5000/v2/": dial tcp 192.168.29.16:5000: i/o timeout```

  - On my backend pod I see the below logs
  ```2024/03/15 11:08:42 [INFO] Successfully stitched ZIPFILE for TheHive-5-v1-a1c456ec161b42be5c18f9f5a556d1a6
2024/03/15 11:08:42 [INFO] Dockerfile: generated/TheHive_5_v1-a1c456ec161b42be5c18f9f5a556d1a6/Dockerfile
2024/03/15 11:08:42 [INFO] Checking for api with ID a1c456ec161b42be5c18f9f5a556d1a6
2024/03/15 11:08:42 [INFO] Updating a user (admin) that has the role admin with 1 apps and 1 orgs. Org updater: true
2024/03/15 11:08:42 [INFO] API LENGTH FOR TheHive_5_v1: 371229, ID: a1c456ec161b42be5c18f9f5a556d1a6
2024/03/15 11:08:42 [INFO] registry name: 192.168.29.16:5000
2024/03/15 11:08:42 contextDir: /app/generated/TheHive_5_v1-a1c456ec161b42be5c18f9f5a556d1a6/
2024/03/15 11:08:42 [INFO] Backend running on: ip-X-X-X-X.us-west-1.compute.internal
2024/03/15 11:09:22 [ERROR] shuffle-app-builder job failed with error: %!s(<nil>)
2024/03/15 11:09:27 [ERROR] Docker build error: [ERROR] failed to fetch shuffle-app-builder status: jobs.batch "shuffle-app-builder" not found```

So, how can I rectify this issue?

**Comment by cloudifyopsblog** [comment]
Hello @frikky  Any update on this?

Can you give me some alternatives on how/where I can store the custom-built apps?

**Comment by MaximeWewer** [comment]
Hi @cloudifyopsblog,

I had the same problem. To solve this you need to provide to your backend a local registry with TLS enable, it's mandatory.

This is how I do : 

1. Create a job to generate certs. I use this method but you can generate manually certs and append it in a secret.
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: registry-tls-certs-creator
  namespace: shuffle
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: registry-tls-secret-creator
  namespace: shuffle
rules:
- apiGroups: [ "" ]
  resources: [ "secrets" ]
  verbs: [ "create", "patch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: registry-tls-certs-creator
  namespace: shuffle
subjects:
- kind: ServiceAccount
  name: registry-tls-certs-creator
roleRef:
  kind: Role
  name: registry-tls-secret-creator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: registry-tls-create-certs
  namespace: shuffle
spec:
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: registry-tls-certs-creator
      initContainers:
      - command:
        - /bin/ash
        - -c
        - |
          function createKey() {
            NAME=$1
            openssl genrsa -out ${NAME}.key 2048
            echo "created ${NAME}.key"
          }

          function createSigningRequest() {
            NAME=$1
            openssl req -new -key ${NAME}.key -extensions 'v3_req' -out ${NAME}.csr -config <(generateServerConfig)
            echo "created ${NAME}.csr"
          }

          function generateServerConfig() {
            cat<<EOF
            [req]
            distinguished_name = req_distinguished_name
            x509_extensions = v3_req
            prompt = no
            [req_distinguished_name]
            CN = registry
            [v3_req]
            keyUsage = keyEncipherment, dataEncipherment
            extendedKeyUsage = serverAuth
            subjectAltName = DNS:localhost,DNS:registry
          EOF
          }

          function signCertificate() {
            INCSR=$1 OUTCRT=$2 CA_CRT=$3 CA_KEY=$4
            openssl x509 -req -in $INCSR -CA $CA_CRT -CAkey $CA_KEY -CAcreateserial -days 365 -out $OUTCRT -extensions v3_req -extfile <(generateServerConfig)
          }

          function secretJson {
            NAME=$1
            cat<<EOF
            {
              "apiVersion": "v1",
              "kind": "Secret",
              "data": {
                "ca.crt": "$(base64 -w 0 ./ca.crt)",
                "tls.crt": "$(base64 -w 0 ./${NAME}.crt)",
                "tls.key": "$(base64 -w 0 ./${NAME}.key)"
              },
              "metadata": {
                "name": "${NAME}"
              },
              "type": "kubernetes.io/tls"
            }
          EOF
          }

          function createCertSecret {
            NAME=$1
            secretJson ${NAME} >> ${NAME}.json
          }

          cd /secret

          # Create a CA key and cert for signing other certs
          createKey ca
          openssl req -x509 -new -nodes -key ca.key -days 365 -out ca.crt -subj "/CN=My Custom CA"

          createKey registry-tls
          createSigningRequest registry-tls
          signCertificate registry-tls.csr registry-tls.crt ca.crt ca.key
          createCertSecret registry-tls
        image: alpine/openssl
        imagePullPolicy: IfNotPresent
        name: create-certs
        volumeMounts:
        - mountPath: /secret
          name: secret
      containers:
      - image: alpine/curl
        name: apply-certs
        imagePullPolicy: IfNotPresent
        command:
        - /bin/ash
        - -c
        - |
          export APISERVER=https://kubernetes.default.svc
          export SERVICEACCOUNT=/var/run/secrets/kubernetes.io/serviceaccount
          export NAMESPACE=$(cat ${SERVICEACCOUNT}/namespace)
          export TOKEN=$(cat ${SERVICEACCOUNT}/token) 
          export CACERT=${SERVICEACCOUNT}/ca.crt

          function uploadSecret {
            NAME=$1
            curl \
              --cacert ${CACERT} \
              --header "Authorization: Bearer ${TOKEN}" \
              --header "Content-Type: application/json" \
              -X POST ${APISERVER}/api/v1/namespaces/${NAMESPACE}/secrets \
              --data "$(tr -d '\n' < /secret/${NAME}.json)" \
              > /dev/null || echo "error uploading ${NAME} secret: $?"
          }

          uploadSecret registry-tls
        volumeMounts:
        - mountPath: /secret
          name: secret
      volumes:
      - name: secret
        emptyDir:
          medium: Memory
```

2. Deploy your local registry
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
  namespace: shuffle
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: YOUR_STORAGECLASS_NAME
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: shuffle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: registry:3
        ports:
        - containerPort: 5000
        env:
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: "/certs/tls.crt"
        - name: REGISTRY_HTTP_TLS_KEY
          value: "/certs/tls.key"
        volumeMounts:
        - name: registry-storage
          mountPath: /var/lib/registry
        - name: tls-certificates
          mountPath: "/certs"
      volumes:
      - name: registry-storage
        persistentVolumeClaim:
          claimName: registry-pvc
      - name: tls-certificates
        secret:
          secretName: registry-tls
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: shuffle
spec:
  selector:
    app: registry
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
```

3. Edit env var of your Shuffle backend to change REGISTRY_URL
```
backend:
  extraEnvVars:
    - name: REGISTRY_URL
       value: "registry:5000"
```

@frikky @P4sca1 

It might be relevant to indicate in the doc that a local registry is mandatory to save customs applications.
If my example seems relevant to you, why add it as an optional element to the new version of the helm chart? :D
