### ISSUE TITLE
when put Orborus on single server,  Can't subflow triggers  resolve shuffle-backend ?

### ISSUE THREAD

**Issue by githubhzj** [Shuffle/Shuffle#1371]
when i run the workflow ,follow errors displayed:
```
ConnectionError - HTTPConnectionPool(host='shuffle-backend', port=5001): Max retries exceeded with url: /api/v1/workflows/4669437e-5054-4a74-826b-96e738a1e3b5/execute?source_workflow=0868874e-536e-4102-905d-60dd1789419a&source_auth=cc1337c7-f97b-464d-8f22-ffa5840bc7c2&source_node=22c0bef9-90d5-4fa3-88a5-31d2b6b092e2&source_execution=d83066f8-5331-4a5f-9b05-160d802903d7&start=b9f0ef26-9c52-4f5b-97cc-9b5d7775a1c2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6055c23490>: Failed to establish a new connection: [Errno -2] Name does not resolve'))
```
how to handle this problem ?    thanks any more
![image](https://github.com/Shuffle/Shuffle/assets/45533210/e5fb4cce-b856-4dfc-9e36-18018b02a315)

**Comment by githubhzj** [comment]
**MY Orborus Config**
```
version: '3'
services:
  orborus:
    image: ghcr.io/shuffle/shuffle-orborus:latest
    container_name: shuffle-orborus
    hostname: shuffle-orborus
    networks:
      - shuffle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SHUFFLE_APP_SDK_TIMEOUT=300
      - SHUFFLE_APP_SDK_VERSION=1.3.1
      - SHUFFLE_ORBORUS_EXECUTION_CONCURRENCY=10 # The amount of concurrent executions Orborus can handle. 
      - SHUFFLE_ORBORUS_EXECUTION_TIMEOUT=600
      - ENVIRONMENT_NAME=Shuffle
      - BASE_URL=http://192.168.253.32:5001
      - DOCKER_API_VERSION=1.40
      - SHUFFLE_BASE_IMAGE_NAME=shuffle
      - SHUFFLE_BASE_IMAGE_REGISTRY=ghcr.io
      - SHUFFLE_BASE_IMAGE_TAG_SUFFIX="-1.3.1"
      - SHUFFLE_STATS_DISABLED=true
      - CLEANUP=true
      - ORG_ID=Shuffle
      - SHUFFLE_WORKER_VERSION=latest
    restart: unless-stopped
networks:
  shuffle:
    driver: bridge
```
