### ISSUE TITLE
Shuffle Integration with Canonical microk8s environment

### ISSUE THREAD

**Issue by Petix992** [Shuffle/Shuffle#1458]
**Describe the bug**
Whenever I try generating an app from OpenAPI file, the frontend shows me a generic syntax error. However, the App is made available for creating workflows, but it doesn't work, leaving workflows in pending status. Indeed, the app does not exist in microk8s. 
The behaviour is quite different from the one on docker environment

On my microk8s environment it seems that the images is being generated through a job:

```
NAME                  STATUS    COMPLETIONS   DURATION   AGE
shuffle-app-builder   Running   0/1           12m        12m
```

I've seen that the job should create the image using kaniko, but the status is running indefinitely

I have set my configuration file so that it points to local microk8s registry on localhost:32000, but it didn't work. There are some integrations with containerd that I am missing?

```
Name:             shuffle-app-builder
Namespace:        shuffle
Selector:         batch.kubernetes.io/controller-uid=8ae10a41-7d18-4247-92f2-139d7f3e6b05
Labels:           batch.kubernetes.io/controller-uid=8ae10a41-7d18-4247-92f2-139d7f3e6b05
                  batch.kubernetes.io/job-name=shuffle-app-builder
                  controller-uid=8ae10a41-7d18-4247-92f2-139d7f3e6b05
                  job-name=shuffle-app-builder
Annotations:      <none>
Parallelism:      1
Completions:      1
Completion Mode:  NonIndexed
Suspend:          false
Backoff Limit:    6
Start Time:       Thu, 18 Jul 2024 14:10:45 +0000
Pods Statuses:    1 Active (0 Ready) / 0 Succeeded / 0 Failed
Pod Template:
  Labels:  batch.kubernetes.io/controller-uid=8ae10a41-7d18-4247-92f2-139d7f3e6b05
           batch.kubernetes.io/job-name=shuffle-app-builder
           controller-uid=8ae10a41-7d18-4247-92f2-139d7f3e6b05
           job-name=shuffle-app-builder
  Containers:
   kaniko:
    Image:      gcr.io/kaniko-project/executor:latest
    Port:       <none>
    Host Port:  <none>
    Args:
      --verbosity=debug
      --dockerfile=./Dockerfile
      --context=dir:///app/generated/Urlscanio-f41eb22c74e16c010d9dbe411e79d39a/
      --skip-tls-verify
      --destination=MY-NODE-IP:32000/frikky/shuffle:someapp_version
    Environment:  <none>
    Mounts:
      /app/generated from kaniko-workspace (rw)
  Volumes:
   kaniko-workspace:
    Type:          PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:     backend-apps-claim
    ReadOnly:      false
  Node-Selectors:  node=k8-academy
  Tolerations:     <none>
Events:            <none>
```
This is the envs configuration I used

```
apiVersion: v1
data:
  BACKEND_HOSTNAME: shuffle-backend
  BACKEND_PORT: "5001"
  BASE_URL: http://shuffle-backend:5001
  DATASTORE_EMULATOR_HOST: shuffle-database:8000
  DB_LOCATION: /mnt/shuffle-data/open-search
  DOCKER_API_VERSION: "1.40"
  ENVIRONMENT_NAME: Shuffle
  FRONTEND_PORT: "3001"
  FRONTEND_PORT_HTTPS: "3443"
  HTTP_PROXY: ""
  HTTPS_PROXY: ""
  ORBORUS_CONTAINER_NAME: "\t\t\t\t"
  ORG_ID: Shuffle
  OUTER_HOSTNAME: shuffle-backend
  SHUFFLE_APP_DOWNLOAD_LOCATION: https://github.com/shuffle/python-apps
  SHUFFLE_APP_FORCE_UPDATE: "false"
  SHUFFLE_APP_HOTLOAD_FOLDER: /shuffle-apps
  SHUFFLE_APP_HOTLOAD_LOCATION: ./shuffle-apps
  SHUFFLE_BASE_IMAGE_NAME: shuffle
  SHUFFLE_BASE_IMAGE_REGISTRY: ghcr.io
  SHUFFLE_BASE_IMAGE_TAG_SUFFIX: -1.0.0
  SHUFFLE_CHAT_DISABLED: "false"
  SHUFFLE_CONTAINER_AUTO_CLEANUP: "false"
  SHUFFLE_DEFAULT_APIKEY: ""
  SHUFFLE_DEFAULT_PASSWORD: ""
  SHUFFLE_DEFAULT_USERNAME: ""
  SHUFFLE_DOWNLOAD_AUTH_BRANCH: ""
  SHUFFLE_DOWNLOAD_AUTH_PASSWORD: ""
  SHUFFLE_DOWNLOAD_AUTH_USERNAME: ""
  SHUFFLE_DOWNLOAD_WORKFLOW_BRANCH: ""
  SHUFFLE_DOWNLOAD_WORKFLOW_LOCATION: ""
  SHUFFLE_DOWNLOAD_WORKFLOW_PASSWORD: ""
  SHUFFLE_DOWNLOAD_WORKFLOW_USERNAME: ""
  SHUFFLE_ELASTIC: "true"
  SHUFFLE_ENCRYPTION_MODIFIER: ""
  SHUFFLE_FILE_LOCATION: /shuffle-files
  SHUFFLE_LOGS_DISABLED: "false"
  SHUFFLE_OPENSEARCH_APIKEY: ""
  SHUFFLE_OPENSEARCH_CERTIFICATE_FILE: ""
  SHUFFLE_OPENSEARCH_CLOUDID: ""
  SHUFFLE_OPENSEARCH_INDEX_PREFIX: ""
  SHUFFLE_OPENSEARCH_PASSWORD: admin
  SHUFFLE_OPENSEARCH_PROXY: ""
  SHUFFLE_OPENSEARCH_SKIPSSL_VERIFY: "true"
  SHUFFLE_OPENSEARCH_URL: https://opensearch:9200
  SHUFFLE_OPENSEARCH_USERNAME: admin
  SHUFFLE_ORBORUS_STARTUP_DELAY: "\t\t"
  SHUFFLE_PASS_APP_PROXY: "FALSE"
  SHUFFLE_PASS_WORKER_PROXY: "TRUE"
  SHUFFLE_RERUN_SCHEDULE: "300"
  SSO_REDIRECT_URL: ""
  TZ: "Europe/Amsterdam \t\t\t\t\t"
  IS_KUBERNETES: "true"
  REGISTRY_URL: "MY-NODE-IP:32000"
  REGISTRY_AUTH: "false"
  SHUFFLE_KUBERNETES_WORKER: "ghcr.io/shuffle/shuffle-worker:nightly"
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: backend-env
  name: env

```

**To Reproduce**
1. Install Microk8s
2. Install shuffle with all-in-one.yaml
3. Insert any OpenApi Json trying to create an application

A description of what you expected to happen.

The application is created and the relative image is generated into microk8s.
