### ISSUE TITLE
Add well-known Kubernetes labels to shuffle-managed resources

### ISSUE THREAD

**Issue by P4sca1** [Shuffle/Shuffle#1534]
Shuffle manages Kubernetes resources, namely workers and apps.
I propose adding well-known Kubernetes labels to these resources to make them targetable using label selectors, e.g. for Network Policies.
Here you can find a list of recommended labels: https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels

**Worker labels:**
```yaml
metadata:
  labels:
    app.kubernetes.io/name: shuffle-worker
    app.kubernetes.io/instance: shuffle-worker-SOME_ID_IF_AVAILABLE
    app.kubernetes.io/version: WORKER_VERSION_IF_APPLICABLE
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: shuffle
    app.kubernetes.io/managed-by: shuffle
```
instance and version could be left out if no appropriate value is available.

**App labels:**
```yaml
metadata:
  labels:
    app.kubernetes.io/name: APP_NAME
    app.kubernetes.io/instance: APP_NAME_SOME_ID_IF_AVAILABLE
    app.kubernetes.io/version: APP_VERSION
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: shuffle
    app.kubernetes.io/managed-by: shuffle
```
