### ISSUE TITLE
Add reference possibility in app creation 

### ISSUE THREAD

**Issue by frikky** [Shuffle/Shuffle#386]
Follow in OpenAPI's footsteps and make references possible for close to everything. Example for actions:

```
actions:
- name: action1
  ref: file:./src/action1.yaml
- name: action2
  ref: #ref/action2
- name: action3
  ref: https://shuffler.io/apps/app_id/action3.yaml

ref:
  action2:
    name: ...
    description: ...
    parameters: 
      - name: ...  
```
