### ISSUE TITLE
Azure AAD SSO Error

### ISSUE THREAD

**Issue by merlinxcy** [Shuffle/Shuffle#883]
l config the Azure AAD try to use SSO
![image](https://user-images.githubusercontent.com/18378246/174568557-34b419e3-cbd5-40ca-a346-97f092824461.png)

![image](https://user-images.githubusercontent.com/18378246/174568633-7d4b841e-2cd5-4507-8bf8-23bb11574192.png)

l found this Error Info.
![image](https://user-images.githubusercontent.com/18378246/174568814-9b8e815a-688e-4d83-a476-1d33ffb3b5b5.png)

How can l change the redirect URI

**Comment by merlinxcy** [comment]
https://login.microsoftonline.com/XXXXXoauth2/v2.0/authorize?client_id=27be2e1d-a8fa-46a0-b5cf-64653693d257&response_type=code&scope=openid&redirect_uri=http%3A%2F%2Fshuffle-backend%3A5001%2Fapi%2Fv1%2Flogin_openid&


how can l change the redirect_uri in shuffle

**Comment by frikky** [comment]
> Maybe this one ![image](https://user-images.githubusercontent.com/18378246/174582366-a880992d-20f1-48f8-be1e-f47b97aed629.png)

Hey! It is indeed the BASE_URL that needs changing. Use your public URL for Shuffle there :)

**Comment by merlinxcy** [comment]
![image](https://user-images.githubusercontent.com/18378246/174586026-55f0c807-400f-48f4-a576-82ec271d8ad6.png)
l have changed it, but the backend return fail

**Comment by frikky** [comment]
> ![image](https://user-images.githubusercontent.com/18378246/174586026-55f0c807-400f-48f4-a576-82ec271d8ad6.png) l have changed it, but the backend return fail

Check logs please. What do they say? 

docker logs shuffle-backend

**Comment by merlinxcy** [comment]
[root@ip-172-31-9-91 Shuffle]# docker attach shuffle-backend

2022/06/20 10:51:27 State: org=7be97d1f-fce7-4d6f-b12a-1c5f583cfd77&challenge=XXXX&redirect=https%3A%2F%2Fec2-13-57-209-228.us-west-1.compute.amazonaws.com%3A3443%2Fapi%2Fv1%2Flogin_openid
2022/06/20 10:51:29 OpenID return BODY: {"error":"invalid_client","error_description":"AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.\r\nTrace ID: 9fcf4b04-cf50-4e2f-8aae-adabc65d3a01\r\nCorrelation ID: c309d6cf-a61e-4001-b3c7-40178fd5a381\r\nTimestamp: 2022-06-20 10:51:29Z","error_codes":[7000218],"timestamp":"2022-06-20 10:51:29Z","trace_id":"9fcf4b04-cf50-4e2f-8aae-adabc65d3a01","correlation_id":"c309d6cf-a61e-4001-b3c7-40178fd5a381","error_uri":"https://login.microsoftonline.com/error?code=7000218"}
2022/06/20 10:51:29 Userinfo endpoint: https://login.microsoftonline.com/60ea294c-db44-41b2-a35c-12aaebe76754/oauth2/v2.0/userinfo
2022/06/20 10:51:29 [WARNING] Error in Openid marshal (2): unexpected end of JSON input

**Comment by merlinxcy** [comment]
![image](https://user-images.githubusercontent.com/18378246/174586605-7ff5a004-db01-4dd9-a163-e35816e994c4.png)
Here is my config

**Comment by frikky** [comment]
Hey! Due to the fact that I can only see three fields for OpenID (should be 4), I think it may simply be an old version of Shuffle you're running.

Please update to the latest :+1:

**Comment by merlinxcy** [comment]
```
frikky/shuffle                           archive.today_1.0.0                       c81678011b3d   4 hours ago     292MB
<none>                                   <none>                                    c0d249746e4b   4 hours ago     292MB
frikky/shuffle                           archive.org_1.0.0                         7035f9f261da   4 hours ago     292MB
<none>                                   <none>                                    df54dc816652   4 hours ago     292MB
frikky/shuffle                           ad-ldap_1.0.0                             eb180f446029   4 hours ago     297MB
frikky/shuffle                           active-directory_1.0.0                    e6ea27c49b9c   4 hours ago     297MB
<none>                                   <none>                                    2274ceec8792   4 hours ago     297MB
<none>                                   <none>                                    47f3bc07ef94   4 hours ago     884MB
registry.hub.docker.com/frikky/shuffle   testing_1.0.0                             bb1c0bd81599   4 days ago      292MB
frikky/shuffle                           app_sdk_grpc                              210769419a98   4 weeks ago     315MB
frikky/shuffle                           app_sdk                                   5ebacd8d4eb6   4 weeks ago     292MB
ghcr.io/frikky/shuffle-frontend          latest                                    685dcf8ac6a2   7 weeks ago     185MB
ghcr.io/frikky/shuffle-worker            latest                                    422cf8d5bf3b   7 weeks ago     44.3MB
ghcr.io/frikky/shuffle-backend           latest                                    91e830aa774b   7 weeks ago     53.6MB
ghcr.io/frikky/shuffle-orborus           latest                                    a717e06ff627   7 weeks ago     29.1MB
opensearchproject/opensearch             1.2.4                                     6842d435e62e   4 months ago    827MB
golang                                   1.17.2-buster                             060ae053525c   8 months ago    884MB
registry.hub.docker.com/frikky/shuffle   snort3_1.0.0                              0d67ad94da8f   9 months ago    641MB
ghcr.io/frikky/shuffle-app_sdk           0.8.97                                    4cb8d9788646   12 months ago   44.8MB
```

**Comment by frikky** [comment]
What does your docker-compose.yml file look like? You may need to change the frontend and backend to version 1.0.2

![image](https://user-images.githubusercontent.com/5719530/174591380-edfab2d3-d53c-4c1c-b40c-be0fa4824c39.png)

**Comment by merlinxcy** [comment]
```
services:
  frontend:
    image: ghcr.io/frikky/shuffle-frontend:latest
    container_name: shuffle-frontend
    hostname: shuffle-frontend
    ports:
      - "${FRONTEND_PORT}:80"
      - "${FRONTEND_PORT_HTTPS}:443"
    networks:
      - shuffle
    environment:
      - BACKEND_HOSTNAME=${BACKEND_HOSTNAME}
    restart: unless-stopped
    depends_on:
      - backend
  backend:
    image: ghcr.io/frikky/shuffle-backend:latest
    container_name: shuffle-backend
    hostname: ${BACKEND_HOSTNAME}
    # Here for debugging:
    ports:
      - "${BACKEND_PORT}:5001"
    networks:
      - shuffle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${SHUFFLE_APP_HOTLOAD_LOCATION}:/shuffle-apps:z
      - ${SHUFFLE_FILE_LOCATION}:/shuffle-files:z
    env_file: .env
    environment:
      - SHUFFLE_APP_HOTLOAD_FOLDER=/shuffle-apps
      - SHUFFLE_FILE_LOCATION=/shuffle-files
    restart: unless-stopped
  orborus:
    image: ghcr.io/frikky/shuffle-orborus:latest
    container_name: shuffle-orborus
    hostname: shuffle-orborus
    networks:
      - shuffle
      
```
it seem latest
